### ISSUE TITLE
Add support for ENUMs as a ThingProperty type (ThingDataType?)

### ISSUE THREAD

**Issue by madb1lly** [mozilla-iot/webthing-arduino#103]
Hi all,

I want to be able to define WebThings with enumerated types for their properties but the Arduino library doesn't currently support it. I'm assuming that it's not trivial to add this otherwise it might have already been done following discussion we had on this subject almost a year ago. I would still find it very helpful to be able to define ThingPropertys with enumerated types.

Cheers :slightly_smiling_face:

**Comment by mrstegeman** [comment]
They're actually already supported. See [here](https://github.com/mozilla-iot/webthing-arduino/blob/e0f43af13b1edce7230983dfe045ef899c1361eb/examples/RGBLamp/RGBLamp.ino#L33) and [here](https://github.com/mozilla-iot/webthing-arduino/blob/e0f43af13b1edce7230983dfe045ef899c1361eb/examples/RGBLamp/RGBLamp.ino#L105) for example usage.
