### ISSUE TITLE
BME280 - Temp, press + humd - Temp not working.

### ISSUE THREAD

**Issue by meatalhead** [mozilla-iot/webthing-arduino#113]
I've just created a webthing through a ESP8266 with a BME280. If I just add a single property of temperature it works fine however if I add pressure and humidity then temperature stops working. Has anyone else had this problem?

**Comment by mrstegeman** [comment]
See the configuration section of the [README](https://github.com/mozilla-iot/webthing-arduino/blob/master/README.md#configuration).

> * If you have a complex device with large thing descriptions, you may need to
>   increase the size of the JSON buffers. The buffer sizes are configurable as
>   such:
>
>     ```cpp
>     // By default, buffers are 256 bytes for small documents, 1024 for larger ones
>
>     // To use a pre-defined set of larger JSON buffers (4x larger)
>     #define LARGE_JSON_BUFFERS 1
>
>     // Else, you can define your own size
>     #define SMALL_JSON_DOCUMENT_SIZE <something>
>     #define LARGE_JSON_DOCUMENT_SIZE <something>
>
>     #include <Thing.h>
>     #include <WebThingAdapter.h>
>     ```

There's also a BME280 [example](https://github.com/mozilla-iot/webthing-arduino/blob/master/examples/BME280/BME280.ino), which uses `LARGE_JSON_BUFFERS`.
