### ISSUE TITLE
New ArduinoJSON beta doesn't compile with ESP8266

### ISSUE THREAD

**Issue by markbeee** [mozilla-iot/webthing-arduino#14]
From version 6.0.0 (beta) Arduino JSON library doesn't compile with webthing-arduino/ ESP8266.

Quote from [https://github.com/bblanchon/ArduinoJson/issues/760] 
"Indeed ArduinoJson 6 replaced the concept of JsonBuffer with the concept of JsonDocument.
To fix this error, you need either:
Downgrade ArduinoJson to 5.x (recommended as v6 is still in beta)
Upgrade your program to work with ArduinoJson 6"

**Comment by hobinjk** [comment]
According to the ArduinoJson website version 6 will be in beta for the rest of 2018 so I think the correct option is to require the use of version 5.

**Comment by rzr** [comment]
Please see if this can be tweaked in make files I just added.

**Comment by willdurand** [comment]
@hobinjk the work to upgrade from ArduinoJson 5 to 6 does not look huge: https://arduinojson.org/v6/doc/upgrade/. Would it make sense to upgrade?

Supporting both versions would be doable, but would it make sense?

**Comment by matiasdelellis** [comment]
Hi, it's already stable, so IMHO is a good time to update this library.. :smiley: 

 * https://arduinojson.org/2019/03/05/version-6-9-0/

Thanks for all.

**Comment by matiasdelellis** [comment]
@markbeee @rzr @willdurand @novski 
Sorry to mention you with @ :sweat_smile: 

@hobinjk is working on this in the pull request #95 
.... and needs to be tested.  :grimacing: 

Thanks and regards,
Matias,

**Comment by rzr** [comment]
If you update it please also try other sample apps built with top makefile

**Comment by rzr** [comment]
Relate-to: https://github.com/mozilla-iot/webthing-arduino/pull/95
