### ISSUE TITLE
Add type Thing

### ISSUE THREAD

**Issue by Citrullin** [mozilla-iot/webthing-arduino#144]
Add 
```
"@type": "Thing"
```

**Comment by benfrancis** [comment]
My understanding is that this isn't actually necessary as it's assumed by WoT TD consumers?

**Comment by Citrullin** [comment]
> My understanding is that this isn't actually necessary as it's assumed by WoT TD consumers?

Well, yes, but apparently it makes some problems in some use-cases. And it doesn't really hurt. So, why not?

**Comment by benfrancis** [comment]
> Well, yes, but apparently it makes some problems in some use-cases.

Can you be more specific?

> And it doesn't really hurt. So, why not?

Unnecessary verbosity.

**Comment by Citrullin** [comment]
> 
> 
> > Well, yes, but apparently it makes some problems in some use-cases.
> 
> Can you be more specific?
> 
> > And it doesn't really hurt. So, why not?
> 
> Unnecessary verbosity.

It was mentioned in one meeting. I don't remember anymore. Well, yes it is verbose. It's already a very verbose JSON in general. You can also question JSON for small devices in general. On the other hand the WoT TD doesn't get requested very often. You can cache it easily. Or use a discovery service which caches it. So, I don't see the verbose part as not such a big deal.
