### ISSUE TITLE
ESP8266 analogread crashes Wifi

### ISSUE THREAD

**Issue by anu1905** [mozilla-iot/webthing-arduino#17]
How can I read an analogvalue using an ESP8266 device (wemos) with Arduino IDE, but without crashing the gateway? The gateway crashes upon using analogRead(A0). I tried several options-delay( ), yield ( ). I'm a newbie at programming. Could someone help me with a solution?

**Comment by hobinjk** [comment]
Sorry for the delay in getting to this! What sort of crash do you get? Can you share the full code you're trying to run?
