### ISSUE TITLE
Get property value before setting it.

### ISSUE THREAD

**Issue by thomas-vl** [mozilla-iot/webthing-arduino#30]
Hi All,

Just a question, in all the examples for a Led light the properties are 'Set' on setup.
Practically, if my Arduino is restarted (or crashes) my Led turns off

Is there is any way to get the property values before they are 'set' so that after a restart/crash my led turns back in to the status it was.

Regards,

Thomas

**Comment by thomas-vl** [comment]
Thanks for the tip!

Now when the device reboots it grabs the values from EEPROM.
I'll do some major code refactoring and then post my code.

**Comment by hobinjk** [comment]
Great! Glad to hear it.
