### ISSUE TITLE
Support readOnly properties.

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/webthing-arduino#31]

**Comment by Nca78** [comment]
I agree with this request. I made a test air quality thing with an ESP32, it's obviously only *reporting* AQI, but the UI lets me enter a value ?
![image](https://user-images.githubusercontent.com/17949850/57911945-53af7e80-78b3-11e9-93ce-a03f9fa78cb7.png)

**Comment by mrstegeman** [comment]
This has been done for a while.
