### ISSUE TITLE
Async behavior

### ISSUE THREAD

**Issue by lgLindstrom** [mozilla-iot/webthing-arduino#36]
I have studied the led example. Although is uses a async webserver you still need to "POLL" propertys to detect changes. 
Should it not be better to provide possibilities for a callback when a property is changed ?

**Comment by hobinjk** [comment]
Callback registration would definitely be a nice thing to have for the library. The main question I'd have is whether it has a significant memory impact or could easily be implemented in a way that it could be selectively disabled on platforms where it wouldn't have benefits (i.e. the WiFi101WebThingAdapter for arduino boards)

**Comment by lgLindstrom** [comment]
Will this work ( not sure about correct syntax, still struggling with C++
.. )

class BoolThingProperty : ThingProperty {
     public
BoolThingProperty

}



tors 1 nov. 2018 kl 22:17 skrev James Hobin <notifications@github.com>:

**Comment by lgLindstrom** [comment]
Hi
I've looked a little bit on your code and noticed that "handleThingPropertyGet" in ESPWebThingAdapter.h is called repeatedly.
This is a bit confusing because I cant see any HTTP access to my device. Can you comment on this ?

**Comment by hobinjk** [comment]
`handleThingPropertyGet` should be called repeatedly in response to thing-url-adapter's polling. It definitely shouldn't be called if there's no HTTP access so I'm not sure what could be going on there.

**Comment by lgLindstrom** [comment]
Hmm,,, I added asynchronous behavior to my local clone,, how do I upload it ???

**Comment by lgLindstrom** [comment]
Hi
I added a PR for my changes but it seems that I not is accepted. This is my first PR ever so I am not sure why. Can you direct me to some good sources of information to understand why it is rejected. I have not understood "anything"  from the sources I found.

**Comment by gigs2go** [comment]
I come from Java API (not C++).
Property has a callback.
In this implementation, adding onSetProperty method pointer should be straightforward - then, when 'setValue' is called on ThingProperty, if method pointer not nulll, call it with ThingPropertyValue.
This would allow my code to specify behaviour when property is changed from 'outside'.
