### ISSUE TITLE
use Arduino or Python with a Linino (Yun, Titan, Industrial101) board?

### ISSUE THREAD

**Issue by novski** [mozilla-iot/webthing-arduino#45]
Some Arduino boards come with a small Linux called openWRT and a surface called Linino.
Im wondering whats better, if its best to use a Arduino based webthing or the python based webthing with such boards?

**Comment by hobinjk** [comment]
webthing-python has more functionality and performs slightly better. webthing-arduino is much smaller and can run on boards with constrained resources. I'd probably recommend webthing-python if the board is beefy enough to run it.
