### ISSUE TITLE
mDNS not working

### ISSUE THREAD

**Issue by energo5** [mozilla-iot/webthing-arduino#51]
Greetings.
I have an "gateway" installed on "orange pi zero" according to this instruction https://github.com/mozilla-iot/gateway/blob/master/README.md

Next, I installed on the "esp8266" webthing-arduino according to this instruction https://github.com/mozilla-iot/webthing-arduino

The web interface normally connects to orange pi (screen attached).
![2019-02-21 15 29 23](https://user-images.githubusercontent.com/15855076/53162836-b1069d00-35ee-11e9-9f26-5f37f18258e2.png)

Http-request for esp is also normally processed (screen attached).
![2019-02-21 15 34 23](https://user-images.githubusercontent.com/15855076/53162862-b9f76e80-35ee-11e9-89f4-99309dcd780a.png)

However, when searching for a new device, nothing is found (I attach a screen from the terminal connected to orange pi).
![2019-02-21 15 33 56](https://user-images.githubusercontent.com/15855076/53162869-bf54b900-35ee-11e9-8335-a19b1fc3a006.png)

What could be the reason?

**Comment by hobinjk** [comment]
It's possible that your local network doesn't support mDNS-based discovery. If you use the 'Add Thing by URL' option in the gateway you can manually specify "http://192.168.1.54/things/lamp" which should load properly and work even if the network doesn't want to do discovery.

If that doesn't work, I'd confirm that the gateway and the lamp can talk to each other by running `curl http://192.168.1.54/things/lamp` on the pi.

**Comment by mrstegeman** [comment]
While doing some testing earlier, my Macbook was unable to see my ESP8266 via mDNS (but the other webthing libraries work fine), so I had to manually input the URL. I didn't dig in to figure out what was going on, though.

**Comment by energo5** [comment]
Thanks!

**Comment by lgLindstrom** [comment]
Please, do we have a status update on this issue ?

**Comment by mrstegeman** [comment]
I no longer see issues on either ESP32 or ESP8266. Closing this. Please re-open if there are further issues, but please remember that you can always add your things by URL in the gateway.

**Comment by lazylazyllama** [comment]
I think this is still an issue.

I am writing a small firmware that uses web things and is compatible with esp32 and esp8266.
Here is my code: https://github.com/lazylazyllama/Incendio

So if I run it on a esp32, mdns is working and the gateway detects my device automatically.

But if I run it on a esp8266 it does not work. I can add the device by url and that works, but mdns does not work, which isn't ideal at all.

I even tried the code from here: https://hacks.mozilla.org/2018/04/making-a-web-thing-on-the-esp8266/
and it didn't work either.
