### ISSUE TITLE
esp8266 shutdown on root address

### ISSUE THREAD

**Issue by energo5** [mozilla-iot/webthing-arduino#65]
Good day.
I compile an example laid out here https://github.com/mozilla-iot/webthing-arduino

When I go to http://192.168.1.110/things/led, I get a normal answer:
{"name": "Built-in LED", "href": "/ things / led", "@context": "https://iot.mozilla.org/schemas", "@type": ["OnOffSwitch "," Light "]," properties ": {" on ": {" type ":" boolean "," @ type ":" OnOffProperty "," href ":" / things / led / properties / on "}} }

When I go to at http://192.168.1.110, I see in Arduino in the port monitor:
Exception (28):
epc1 = 0x4020ff9d epc2 = 0x00000000 epc3 = 0x00000000 excvaddr = 0x00000028 depc = 0x00000000
>>> stack >>>
ctx: sys
sp: 3fffdb20 end: 3fffffb0 offset: 01a0
3fffdcc0: 00000020 00000000 3fff136c 402076a9
3fffdcd0: 3fffdd30 00000000 3fff136c 402076e4
...

and esp8266 reboots or shutdown.
Tell me what can be done to prevent such a reboot.

**Comment by mrstegeman** [comment]
This doesn't appear to be happening with the latest version. Closing.
